[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flowtube"
version = "1.0.0"
authors = [
  { name = "Corey Pedersen", email = "coreyped@gmail.com" },
]
description = "A Python package for transport and diffusion calculations in cylindrical flow reactors"
readme = "README.md"
license = "MIT"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
]
keywords = ["flow reactor", "diffusion", "transport", "coated wall reactor", "aerosol", "atmospheric chemistry"]

dependencies = [
    "numpy>=1.18.0",
    "pandas>=1.0.0", 
    "tabulate>=0.8.0",
    "molmass>=2019.1.1",
]

[project.urls]
Homepage = "https://github.com/c-pedersen/flowtube"
Repository = "https://github.com/c-pedersen/flowtube"
Documentation = "https://github.com/c-pedersen/flowtube#readme"
"Bug Tracker" = "https://github.com/c-pedersen/flowtube/issues"

[tool.setuptools]
packages = ["flowtube"]

[tool.setuptools.package-data]
flowtube = ["py.typed", "*.pyi"]

[tool.pyright]
include = ["flowtube"]
exclude = ["**/__pycache__"]
typeCheckingMode = "standard"

[tool.ruff]
line-length = 88
docstring-code-line-length = 72